package com.DevAsh.recbusiness.Home

import android.content.Intent
import android.os.Bundle
import android.view.Window
import android.view.WindowManager
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.DevAsh.recbusiness.Context.ApiContext
import com.DevAsh.recbusiness.Context.TransactionContext
import com.DevAsh.recbusiness.Helper.AlertHelper
import com.DevAsh.recbusiness.Home.Transactions.SingleObjectTransaction
import com.DevAsh.recbusiness.Models.Contacts
import com.DevAsh.recbusiness.R
import com.budiyev.android.codescanner.*
import io.jsonwebtoken.Jwts


class QrScanner : AppCompatActivity() {
    private lateinit var codeScanner: CodeScanner
    var context = this
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_qr_scanner)

        val w: Window = window
        w.setFlags(
            WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
            WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS
        )
        this.window.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
            WindowManager.LayoutParams.FLAG_FULLSCREEN);

        val scannerView = findViewById<CodeScannerView>(R.id.scanner_view)

        codeScanner = CodeScanner(this, scannerView)
        codeScanner.camera = CodeScanner.CAMERA_BACK
        codeScanner.formats = CodeScanner.ALL_FORMATS
        // ex. listOf(BarcodeFormat.QR_CODE)
        codeScanner.autoFocusMode = AutoFocusMode.SAFE // or CONTINUOUS
        codeScanner.scanMode = ScanMode.SINGLE // or CONTINUOUS or PREVIEW
        codeScanner.isAutoFocusEnabled = true // Whether to enable auto focus or not
        codeScanner.isFlashEnabled = false // Whether to enable flash or not

        codeScanner.decodeCallback = DecodeCallback {
            runOnUiThread {
                try {


                    val people = Jwts.parser().setSigningKey(ApiContext.qrKey).parseClaimsJws(it.text).body
                    TransactionContext.selectedUser= Contacts(people["name"].toString(), "+"+people["number"].toString(),people["id"].toString(),people["email"].toString())
                    startActivity(
                        Intent(context, SingleObjectTransaction::class.java)
                    )
                    finish()
                }catch (e:Throwable){
                    println(e)
                   AlertHelper.showAlertDialog(this,
                       "Invalid Qr",
                       "The scanned qr code is invalid and it is not generated by r-pay",
                       object: AlertHelper.AlertDialogCallback {
                           override fun onDismiss() {
                               onBackPressed()
                           }

                           override fun onDone() {
                               onBackPressed()
                           }
                       }
                   )

                }

            }
        }
        codeScanner.errorCallback = ErrorCallback { // or ErrorCallback.SUPPRESS
            runOnUiThread {
                Toast.makeText(this, "Camera initialization error: ${it.message}",
                    Toast.LENGTH_LONG).show()
            }
        }
        codeScanner.startPreview()
    }
}